#!/usr/bin/env bash

# Get domain and subdomain from arguments
domain=$1
subdomain=$2

# Define the subdomains and their IPs
subdomains=("www" "lb-01" "web-01" "web-02")
ips=("100.25.170.196" "100.25.170.196" "18.210.13.239" "18.214.89.149")

# Loop through subdomains and display information
for i in "${subdomains[@]}"; do
  if [ -z "$subdomain" ] || [ "$i" == "$subdomain" ]; then
    echo "The subdomain $i is a A record and points to ${ips[${subdomains[@]} == "$i"]}"
  fi
done
