#!/usr/bin/env bash
# Script to install Nginx and configure to return 'Hello World!'

apt-get update
apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
