#!/usr/bin/env bash
# Script to configure Nginx for redirection

# Redirect /redirect_me to another page with a 301 status
echo "
server {
    listen 80;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/redirect_config

ln -s /etc/nginx/sites-available/redirect_config /etc/nginx/sites-enabled/redirect_config

nginx -s reload
