#!/usr/bin/env bash
# Script to configure a custom 404 page in Nginx

echo "
server {
    listen 80;
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
    location / {
        return 404;
    }
}
" > /etc/nginx/sites-available/custom_404

ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/custom_404

# Create the custom 404 page with the specified text
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

nginx -s reload
