#!/usr/bin/env bash

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

custom_404=$(cat <<EOF
error_page 404 /custom_404.html;
location = /custom_404.html {
    root /var/www/html;
    internal;
}
EOF
)

sed -i "s|server_name _;|server_name _;\n\n\t$custom_404|" /etc/nginx/sites-available/default

service nginx restart
