#!/usr/bin/env bash
# This script pings an IP address 5 times

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS="$1"

echo "Pinging IP address: $IP_ADDRESS"
ping -c 5 $IP_ADDRESS
