#!/usr/bin/env bash
# Configures Nginx to start and listen on port 80 of all active IPv4 IPs

# Ensure nginx is installed
apt-get update
apt-get install -y nginx

# Start nginx service
service nginx start

# Ensure nginx is set to start on boot
systemctl enable nginx
