#!/usr/bin/env bash
# Configures Nginx to listen on port 80 (short version)

sed -i 's/listen\s*\[::\]:80/listen 80/' /etc/nginx/sites-available/default
sed -i 's/listen\s*80\s*default_server/listen 80 default_server/' /etc/nginx/sites-available/default
service nginx restart
