#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using kill

# Find the PID of 4-to_infinity_and_beyond and kill it
PID=$(pgrep -f 4-to_infinity_and_beyond)
if [ -n "$PID" ]; then
    kill "$PID"
fi
