#!/usr/bin/env bash

# Reset UFW rules
ufw --force reset

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow incoming traffic on ports 22, 443, and 80
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

# Enable the firewall
ufw --force enable
