#!/usr/bin/env bash
# Configures ufw firewall to block all incoming traffic except for ports 22, 443, and 80

# Block all incoming traffic
sudo ufw default deny incoming

# Allow incoming SSH traffic
sudo ufw allow 22/tcp

# Allow incoming HTTPS SSL traffic
sudo ufw allow 443/tcp

# Allow incoming HTTP traffic
sudo ufw allow 80/tcp

# Enable the firewall
sudo ufw enable
