#!/usr/bin/env bash
# Configures the /etc/hosts file to meet specific requirements

# Backup the current /etc/hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Writing new entries to the /etc/hosts
echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
