#!/usr/bin/env bash
# Fix the web server to return a page containing "Hello Holberton"

# Install Apache
apt-get update
apt-get install -y apache2

# Create the "Hello Holberton" page
echo "Hello Holberton" > /var/www/html/index.html

# Start Apache
service apache2 start
