#!/usr/bin/env bash
# Configure container to run Nginx as nginx user

# Kill Nginx if running
pkill -f nginx

# Change Nginx config to run as nginx user
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf

# Change listen port to 8080
sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-enabled/default

# Start Nginx
sudo -u nginx service nginx start
