#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user

# Ensure nginx is installed
apt-get update
apt-get install -y nginx

# Update the configuration to run as nginx user
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Restart nginx to apply changes
service nginx restart
