#!/usr/bin/env bash
# Fix Nginx to run as nginx user in 7 lines or less

pkill -f nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx nginx
