#!/usr/bin/env bash
# Configure Nginx to run as nginx user in 7 lines or less

apt-get update
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
pkill -f nginx
nginx -g 'daemon off;'
