#!/usr/bin/env bash
# Configure Nginx to run as nginx user in 7 lines or less
apt-get update -y
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
